# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Gather tools
      run: dotnet tool restore
    - name: Build, pack and push to NuGet.org
      continue-on-error: true
      run: dotnet cake --target=push --nuGetApiKey=${{ secrets.nuGetApiKey }}
  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Gather tools
      run: dotnet tool restore
    - name: Login to DockerHub
      run: docker login --username andeadlier --password ${{ secrets.dockerHubAccessToken }}
    - name: Build, tag and push to DockerHub
      run: dotnet cake ./docker.cake --target=push
